// Questions
var q = [
	'What do you understand in data science that most don&#39;t?',
	'Why will you succeed at this role?',
	'How big was your impact in your last project?',
	'What problems/hurdles have you solved in your last project?',
	'How will you learn teamwork from a team?',
	'How much salary you expect?',
	'How many people used your last project?',
	'How many collaborated on your last project?',
	'How are you understanding your managers feedback?',
	'How will you get started on a new project?',
	'Who would you collaborate with better in a new team?',

	'So what are you working on?',
	'Do you have a demo of your last project?',
	'Where is the tough challenge in your last modelling work?',
	'How does your model work in more detail?',
	'How is your model different?',
	'What are you going to do next?',
	'What&#39;s new about what you build?',
	'What, exactly, makes you different from existing options?',
	'Who was your audience in your last presentation?',
	'How do you know your team need what you&#39;re making?',
	'What obstacles will you face and how will you overcome them?',
	'How will your team find out about you?',
	'What resistance your last team have to overcome to collaborate with you?',
	'What are the key things about your field that your last team don&#39;t understand?',
	'What part of your last project were you building first?',
	'Who was your first user for your last project?',
	'If you get this job, what additional areas might you be able to expand into?',
	'Why did you choose this industry?',
	'What have you learned so far from working on your last project?',
	'Six months from now, what&#39;s going to be your biggest problem?',
	'Where do your new projects come from?',
	'How do you make sure you learn new skills?',
	'What makes new teams want to know you?',
	'Why do the reluctant team mates hold back from working with you?',
	'What are the top things your last teammates want from you?',
	'What has surprised you about your behaviour in a growing team?',
	'What&#39;s an impressive thing you have done?',
	'What do you understand about your last project that many did not?',
	'Why did you pick this role to join this team?',
	'What sql expertise do you have?',
	'Who are other roles you are considering?',
	'What might become your next industry to work in?',
	'Someone just showed us a project like this right before you. I don&#39;t like it. What else are you working on?',
	'What are the most challegening part of this role that you fear most?',
	'How do you usually share work?',
	'How did you meet your last team?',
	'Why did your team get together on that project?',
	'Who in your last project does what?',
	'Who is &quot;the boss&quot;?',
	'What will you do if we don&#39;t fund you?',
	'Would you relocate to Philadelphia?',
	'How do we know your team will stick together?',
	'What else have you built as a project manager?',
	'Are you open to a different role? ',
	'What languages have you built applications or models in?',
	'Tell us about a tough classification problem you solved?',
	'In what ways are you resourceful?',
	'Will you require US work autherization?',
	'Tell us something surprising you have done?',
	'What&#39;s the funniest thing that has happened to you?',
	'What&#39;s the worst thing that has happened?',
	'What&#39;s the biggest mistake you have made?',
	'How long have you been in job search?',
	'How many onsite or technical interviews have you got so far?',
	'What is the next step for you in your career?',
	'Have you ever managed a team of engineers before?',
	'What would be your next project?',

	'How do you know you like this role?',
	'What do you know about this space/product others don&#39;t know?'
];

// Tips
var tips = [
	'Try to have quick and concise answers.',
	'Try to answer in 2 to 3 sentences.',
	'Answer like you would in a conversation, this is not a presentation.',
	'When talking to Hoofar and the other PhillyTalent partners, be substantive, and get straight to the point.',
	'DO NOT BEAT AROUND THE BUSH. Do not hem and haw. "Uhm"s and "uh"s do not show intelligence.',
	'Use precise and concise language. You aren&#39;t revealing anything secret.',
	'He talks quickly, and so do the other PhillyTalent team. Try to match their tempo (as you should when talking to anyone).'
];
